{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "photonops.fullname" . }}-runtime
  labels:
    {{- include "photonops.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecrets.secretStoreName }}
  target:
    name: {{ .Values.runtimeSecret.name }}
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: {{ .Values.externalSecrets.remoteSecretName }}
        property: database_url
    {{ if eq .Values.config.aiProvider "bedrock_mantle" }}
    - secretKey: BEDROCK_API_KEY
      remoteRef:
        key: {{ .Values.externalSecrets.remoteSecretName }}
        property: bedrock_api_key
    {{ end }}
{{- end }}
