{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "photonops.fullname" . }}
  labels:
    {{- include "photonops.labels" . | nindent 4 }}
  annotations:
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.scheme | quote }}
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: {{ .Values.ingress.groupName | quote }}
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    {{ if .Values.ingress.certificateArn }}
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.certificateArn | quote }}
    {{ end }}
    {{ if .Values.ingress.wafv2AclArn }}
    alb.ingress.kubernetes.io/wafv2-acl-arn: {{ .Values.ingress.wafv2AclArn | quote }}
    {{ end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "photonops.fullname" . }}-api
                port: { number: 8000 }
          - path: /health
            pathType: Exact
            backend:
              service:
                name: {{ include "photonops.fullname" . }}-api
                port: { number: 8000 }
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "photonops.fullname" . }}-web
                port: { number: 3000 }
{{- end }}
