apiVersion: v1
kind: Service
metadata:
  name: {{ include "photonops.fullname" . }}-api
  labels:
    {{- include "photonops.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
  ports:
    - { name: http, port: 8000, targetPort: http, protocol: TCP }
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "photonops.fullname" . }}-web
  labels:
    {{- include "photonops.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web
  ports:
    - { name: http, port: 3000, targetPort: http, protocol: TCP }
